/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.content.targeting.rule.mood.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.content.targeting.rule.mood.model.Mood;
import com.liferay.content.targeting.rule.mood.model.MoodModel;
import com.liferay.content.targeting.rule.mood.model.MoodSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Mood service. Represents a row in the &quot;CT_Mood_Mood&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link MoodModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MoodImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MoodImpl
 * @see Mood
 * @see MoodModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class MoodModelImpl extends BaseModelImpl<Mood> implements MoodModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mood model instance should use the {@link Mood} interface instead.
	 */
	public static final String TABLE_NAME = "CT_Mood_Mood";
	public static final Object[][] TABLE_COLUMNS = {
			{ "moodId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "anonymousUserId", Types.BIGINT },
			{ "ruleInstanceId", Types.BIGINT },
			{ "timeToLive", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("moodId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("anonymousUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ruleInstanceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("timeToLive", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table CT_Mood_Mood (moodId LONG not null primary key,companyId LONG,modifiedDate DATE null,anonymousUserId LONG,ruleInstanceId LONG,timeToLive LONG)";
	public static final String TABLE_SQL_DROP = "drop table CT_Mood_Mood";
	public static final String ORDER_BY_JPQL = " ORDER BY mood.anonymousUserId DESC";
	public static final String ORDER_BY_SQL = " ORDER BY CT_Mood_Mood.anonymousUserId DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.content.targeting.rule.mood.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.content.targeting.rule.mood.model.Mood"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.content.targeting.rule.mood.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.content.targeting.rule.mood.model.Mood"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.content.targeting.rule.mood.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.content.targeting.rule.mood.model.Mood"),
			true);
	public static final long ANONYMOUSUSERID_COLUMN_BITMASK = 1L;
	public static final long RULEINSTANCEID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Mood toModel(MoodSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Mood model = new MoodImpl();

		model.setMoodId(soapModel.getMoodId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setAnonymousUserId(soapModel.getAnonymousUserId());
		model.setRuleInstanceId(soapModel.getRuleInstanceId());
		model.setTimeToLive(soapModel.getTimeToLive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Mood> toModels(MoodSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Mood> models = new ArrayList<Mood>(soapModels.length);

		for (MoodSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.content.targeting.rule.mood.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.content.targeting.rule.mood.model.Mood"));

	public MoodModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _moodId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMoodId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _moodId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Mood.class;
	}

	@Override
	public String getModelClassName() {
		return Mood.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("moodId", getMoodId());
		attributes.put("companyId", getCompanyId());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("anonymousUserId", getAnonymousUserId());
		attributes.put("ruleInstanceId", getRuleInstanceId());
		attributes.put("timeToLive", getTimeToLive());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long moodId = (Long)attributes.get("moodId");

		if (moodId != null) {
			setMoodId(moodId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long anonymousUserId = (Long)attributes.get("anonymousUserId");

		if (anonymousUserId != null) {
			setAnonymousUserId(anonymousUserId);
		}

		Long ruleInstanceId = (Long)attributes.get("ruleInstanceId");

		if (ruleInstanceId != null) {
			setRuleInstanceId(ruleInstanceId);
		}

		Long timeToLive = (Long)attributes.get("timeToLive");

		if (timeToLive != null) {
			setTimeToLive(timeToLive);
		}
	}

	@JSON
	@Override
	public long getMoodId() {
		return _moodId;
	}

	@Override
	public void setMoodId(long moodId) {
		_moodId = moodId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getAnonymousUserId() {
		return _anonymousUserId;
	}

	@Override
	public void setAnonymousUserId(long anonymousUserId) {
		_columnBitmask = -1L;

		if (!_setOriginalAnonymousUserId) {
			_setOriginalAnonymousUserId = true;

			_originalAnonymousUserId = _anonymousUserId;
		}

		_anonymousUserId = anonymousUserId;
	}

	@Override
	public String getAnonymousUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getAnonymousUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setAnonymousUserUuid(String anonymousUserUuid) {
	}

	public long getOriginalAnonymousUserId() {
		return _originalAnonymousUserId;
	}

	@JSON
	@Override
	public long getRuleInstanceId() {
		return _ruleInstanceId;
	}

	@Override
	public void setRuleInstanceId(long ruleInstanceId) {
		_columnBitmask |= RULEINSTANCEID_COLUMN_BITMASK;

		if (!_setOriginalRuleInstanceId) {
			_setOriginalRuleInstanceId = true;

			_originalRuleInstanceId = _ruleInstanceId;
		}

		_ruleInstanceId = ruleInstanceId;
	}

	public long getOriginalRuleInstanceId() {
		return _originalRuleInstanceId;
	}

	@JSON
	@Override
	public long getTimeToLive() {
		return _timeToLive;
	}

	@Override
	public void setTimeToLive(long timeToLive) {
		_timeToLive = timeToLive;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Mood.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Mood toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Mood)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MoodImpl moodImpl = new MoodImpl();

		moodImpl.setMoodId(getMoodId());
		moodImpl.setCompanyId(getCompanyId());
		moodImpl.setModifiedDate(getModifiedDate());
		moodImpl.setAnonymousUserId(getAnonymousUserId());
		moodImpl.setRuleInstanceId(getRuleInstanceId());
		moodImpl.setTimeToLive(getTimeToLive());

		moodImpl.resetOriginalValues();

		return moodImpl;
	}

	@Override
	public int compareTo(Mood mood) {
		int value = 0;

		if (getAnonymousUserId() < mood.getAnonymousUserId()) {
			value = -1;
		}
		else if (getAnonymousUserId() > mood.getAnonymousUserId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Mood)) {
			return false;
		}

		Mood mood = (Mood)obj;

		long primaryKey = mood.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		MoodModelImpl moodModelImpl = this;

		moodModelImpl._originalAnonymousUserId = moodModelImpl._anonymousUserId;

		moodModelImpl._setOriginalAnonymousUserId = false;

		moodModelImpl._originalRuleInstanceId = moodModelImpl._ruleInstanceId;

		moodModelImpl._setOriginalRuleInstanceId = false;

		moodModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Mood> toCacheModel() {
		MoodCacheModel moodCacheModel = new MoodCacheModel();

		moodCacheModel.moodId = getMoodId();

		moodCacheModel.companyId = getCompanyId();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			moodCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			moodCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		moodCacheModel.anonymousUserId = getAnonymousUserId();

		moodCacheModel.ruleInstanceId = getRuleInstanceId();

		moodCacheModel.timeToLive = getTimeToLive();

		return moodCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{moodId=");
		sb.append(getMoodId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", anonymousUserId=");
		sb.append(getAnonymousUserId());
		sb.append(", ruleInstanceId=");
		sb.append(getRuleInstanceId());
		sb.append(", timeToLive=");
		sb.append(getTimeToLive());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.liferay.content.targeting.rule.mood.model.Mood");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>moodId</column-name><column-value><![CDATA[");
		sb.append(getMoodId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>anonymousUserId</column-name><column-value><![CDATA[");
		sb.append(getAnonymousUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ruleInstanceId</column-name><column-value><![CDATA[");
		sb.append(getRuleInstanceId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>timeToLive</column-name><column-value><![CDATA[");
		sb.append(getTimeToLive());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Mood.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Mood.class
		};
	private long _moodId;
	private long _companyId;
	private Date _modifiedDate;
	private long _anonymousUserId;
	private long _originalAnonymousUserId;
	private boolean _setOriginalAnonymousUserId;
	private long _ruleInstanceId;
	private long _originalRuleInstanceId;
	private boolean _setOriginalRuleInstanceId;
	private long _timeToLive;
	private long _columnBitmask;
	private Mood _escapedModel;
}