/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.content.targeting.rule.mood.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Mood service. Represents a row in the &quot;CT_Mood_Mood&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.content.targeting.rule.mood.model.impl.MoodModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.content.targeting.rule.mood.model.impl.MoodImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Mood
 * @see com.liferay.content.targeting.rule.mood.model.impl.MoodImpl
 * @see com.liferay.content.targeting.rule.mood.model.impl.MoodModelImpl
 * @generated
 */
@ProviderType
public interface MoodModel extends BaseModel<Mood>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mood model instance should use the {@link Mood} interface instead.
	 */

	/**
	 * Returns the primary key of this mood.
	 *
	 * @return the primary key of this mood
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mood.
	 *
	 * @param primaryKey the primary key of this mood
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mood ID of this mood.
	 *
	 * @return the mood ID of this mood
	 */
	public long getMoodId();

	/**
	 * Sets the mood ID of this mood.
	 *
	 * @param moodId the mood ID of this mood
	 */
	public void setMoodId(long moodId);

	/**
	 * Returns the company ID of this mood.
	 *
	 * @return the company ID of this mood
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this mood.
	 *
	 * @param companyId the company ID of this mood
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the modified date of this mood.
	 *
	 * @return the modified date of this mood
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this mood.
	 *
	 * @param modifiedDate the modified date of this mood
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the anonymous user ID of this mood.
	 *
	 * @return the anonymous user ID of this mood
	 */
	public long getAnonymousUserId();

	/**
	 * Sets the anonymous user ID of this mood.
	 *
	 * @param anonymousUserId the anonymous user ID of this mood
	 */
	public void setAnonymousUserId(long anonymousUserId);

	/**
	 * Returns the anonymous user uuid of this mood.
	 *
	 * @return the anonymous user uuid of this mood
	 */
	public String getAnonymousUserUuid();

	/**
	 * Sets the anonymous user uuid of this mood.
	 *
	 * @param anonymousUserUuid the anonymous user uuid of this mood
	 */
	public void setAnonymousUserUuid(String anonymousUserUuid);

	/**
	 * Returns the rule instance ID of this mood.
	 *
	 * @return the rule instance ID of this mood
	 */
	public long getRuleInstanceId();

	/**
	 * Sets the rule instance ID of this mood.
	 *
	 * @param ruleInstanceId the rule instance ID of this mood
	 */
	public void setRuleInstanceId(long ruleInstanceId);

	/**
	 * Returns the time to live of this mood.
	 *
	 * @return the time to live of this mood
	 */
	public long getTimeToLive();

	/**
	 * Sets the time to live of this mood.
	 *
	 * @param timeToLive the time to live of this mood
	 */
	public void setTimeToLive(long timeToLive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Mood mood);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Mood> toCacheModel();

	@Override
	public Mood toEscapedModel();

	@Override
	public Mood toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}