/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.content.targeting.rule.user.journey.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.content.targeting.rule.user.journey.model.UserJourney;
import com.liferay.content.targeting.rule.user.journey.model.UserJourneyModel;
import com.liferay.content.targeting.rule.user.journey.model.UserJourneySoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the UserJourney service. Represents a row in the &quot;CT_UJ_UserJourney&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link UserJourneyModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserJourneyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserJourneyImpl
 * @see UserJourney
 * @see UserJourneyModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class UserJourneyModelImpl extends BaseModelImpl<UserJourney>
	implements UserJourneyModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user journey model instance should use the {@link UserJourney} interface instead.
	 */
	public static final String TABLE_NAME = "CT_UJ_UserJourney";
	public static final Object[][] TABLE_COLUMNS = {
			{ "userJourneyId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "anonymousUserId", Types.BIGINT },
			{ "ruleInstanceId", Types.BIGINT },
			{ "currentPlid", Types.BIGINT },
			{ "finished", Types.BOOLEAN }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("userJourneyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("anonymousUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ruleInstanceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("currentPlid", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("finished", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE = "create table CT_UJ_UserJourney (userJourneyId LONG not null primary key,companyId LONG,modifiedDate DATE null,anonymousUserId LONG,ruleInstanceId LONG,currentPlid LONG,finished BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table CT_UJ_UserJourney";
	public static final String ORDER_BY_JPQL = " ORDER BY userJourney.anonymousUserId DESC";
	public static final String ORDER_BY_SQL = " ORDER BY CT_UJ_UserJourney.anonymousUserId DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.content.targeting.rule.user.journey.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.content.targeting.rule.user.journey.model.UserJourney"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.content.targeting.rule.user.journey.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.content.targeting.rule.user.journey.model.UserJourney"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.content.targeting.rule.user.journey.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.content.targeting.rule.user.journey.model.UserJourney"),
			true);
	public static final long ANONYMOUSUSERID_COLUMN_BITMASK = 1L;
	public static final long RULEINSTANCEID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static UserJourney toModel(UserJourneySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		UserJourney model = new UserJourneyImpl();

		model.setUserJourneyId(soapModel.getUserJourneyId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setAnonymousUserId(soapModel.getAnonymousUserId());
		model.setRuleInstanceId(soapModel.getRuleInstanceId());
		model.setCurrentPlid(soapModel.getCurrentPlid());
		model.setFinished(soapModel.getFinished());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<UserJourney> toModels(UserJourneySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<UserJourney> models = new ArrayList<UserJourney>(soapModels.length);

		for (UserJourneySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.content.targeting.rule.user.journey.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.content.targeting.rule.user.journey.model.UserJourney"));

	public UserJourneyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _userJourneyId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUserJourneyId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _userJourneyId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UserJourney.class;
	}

	@Override
	public String getModelClassName() {
		return UserJourney.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("userJourneyId", getUserJourneyId());
		attributes.put("companyId", getCompanyId());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("anonymousUserId", getAnonymousUserId());
		attributes.put("ruleInstanceId", getRuleInstanceId());
		attributes.put("currentPlid", getCurrentPlid());
		attributes.put("finished", getFinished());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long userJourneyId = (Long)attributes.get("userJourneyId");

		if (userJourneyId != null) {
			setUserJourneyId(userJourneyId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long anonymousUserId = (Long)attributes.get("anonymousUserId");

		if (anonymousUserId != null) {
			setAnonymousUserId(anonymousUserId);
		}

		Long ruleInstanceId = (Long)attributes.get("ruleInstanceId");

		if (ruleInstanceId != null) {
			setRuleInstanceId(ruleInstanceId);
		}

		Long currentPlid = (Long)attributes.get("currentPlid");

		if (currentPlid != null) {
			setCurrentPlid(currentPlid);
		}

		Boolean finished = (Boolean)attributes.get("finished");

		if (finished != null) {
			setFinished(finished);
		}
	}

	@JSON
	@Override
	public long getUserJourneyId() {
		return _userJourneyId;
	}

	@Override
	public void setUserJourneyId(long userJourneyId) {
		_userJourneyId = userJourneyId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getAnonymousUserId() {
		return _anonymousUserId;
	}

	@Override
	public void setAnonymousUserId(long anonymousUserId) {
		_columnBitmask = -1L;

		if (!_setOriginalAnonymousUserId) {
			_setOriginalAnonymousUserId = true;

			_originalAnonymousUserId = _anonymousUserId;
		}

		_anonymousUserId = anonymousUserId;
	}

	@Override
	public String getAnonymousUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getAnonymousUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setAnonymousUserUuid(String anonymousUserUuid) {
	}

	public long getOriginalAnonymousUserId() {
		return _originalAnonymousUserId;
	}

	@JSON
	@Override
	public long getRuleInstanceId() {
		return _ruleInstanceId;
	}

	@Override
	public void setRuleInstanceId(long ruleInstanceId) {
		_columnBitmask |= RULEINSTANCEID_COLUMN_BITMASK;

		if (!_setOriginalRuleInstanceId) {
			_setOriginalRuleInstanceId = true;

			_originalRuleInstanceId = _ruleInstanceId;
		}

		_ruleInstanceId = ruleInstanceId;
	}

	public long getOriginalRuleInstanceId() {
		return _originalRuleInstanceId;
	}

	@JSON
	@Override
	public long getCurrentPlid() {
		return _currentPlid;
	}

	@Override
	public void setCurrentPlid(long currentPlid) {
		_currentPlid = currentPlid;
	}

	@JSON
	@Override
	public boolean getFinished() {
		return _finished;
	}

	@JSON
	@Override
	public boolean isFinished() {
		return _finished;
	}

	@Override
	public void setFinished(boolean finished) {
		_finished = finished;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			UserJourney.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UserJourney toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (UserJourney)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UserJourneyImpl userJourneyImpl = new UserJourneyImpl();

		userJourneyImpl.setUserJourneyId(getUserJourneyId());
		userJourneyImpl.setCompanyId(getCompanyId());
		userJourneyImpl.setModifiedDate(getModifiedDate());
		userJourneyImpl.setAnonymousUserId(getAnonymousUserId());
		userJourneyImpl.setRuleInstanceId(getRuleInstanceId());
		userJourneyImpl.setCurrentPlid(getCurrentPlid());
		userJourneyImpl.setFinished(getFinished());

		userJourneyImpl.resetOriginalValues();

		return userJourneyImpl;
	}

	@Override
	public int compareTo(UserJourney userJourney) {
		int value = 0;

		if (getAnonymousUserId() < userJourney.getAnonymousUserId()) {
			value = -1;
		}
		else if (getAnonymousUserId() > userJourney.getAnonymousUserId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof UserJourney)) {
			return false;
		}

		UserJourney userJourney = (UserJourney)obj;

		long primaryKey = userJourney.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		UserJourneyModelImpl userJourneyModelImpl = this;

		userJourneyModelImpl._originalAnonymousUserId = userJourneyModelImpl._anonymousUserId;

		userJourneyModelImpl._setOriginalAnonymousUserId = false;

		userJourneyModelImpl._originalRuleInstanceId = userJourneyModelImpl._ruleInstanceId;

		userJourneyModelImpl._setOriginalRuleInstanceId = false;

		userJourneyModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<UserJourney> toCacheModel() {
		UserJourneyCacheModel userJourneyCacheModel = new UserJourneyCacheModel();

		userJourneyCacheModel.userJourneyId = getUserJourneyId();

		userJourneyCacheModel.companyId = getCompanyId();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			userJourneyCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			userJourneyCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		userJourneyCacheModel.anonymousUserId = getAnonymousUserId();

		userJourneyCacheModel.ruleInstanceId = getRuleInstanceId();

		userJourneyCacheModel.currentPlid = getCurrentPlid();

		userJourneyCacheModel.finished = getFinished();

		return userJourneyCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{userJourneyId=");
		sb.append(getUserJourneyId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", anonymousUserId=");
		sb.append(getAnonymousUserId());
		sb.append(", ruleInstanceId=");
		sb.append(getRuleInstanceId());
		sb.append(", currentPlid=");
		sb.append(getCurrentPlid());
		sb.append(", finished=");
		sb.append(getFinished());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append(
			"com.liferay.content.targeting.rule.user.journey.model.UserJourney");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>userJourneyId</column-name><column-value><![CDATA[");
		sb.append(getUserJourneyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>anonymousUserId</column-name><column-value><![CDATA[");
		sb.append(getAnonymousUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ruleInstanceId</column-name><column-value><![CDATA[");
		sb.append(getRuleInstanceId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>currentPlid</column-name><column-value><![CDATA[");
		sb.append(getCurrentPlid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>finished</column-name><column-value><![CDATA[");
		sb.append(getFinished());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = UserJourney.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			UserJourney.class
		};
	private long _userJourneyId;
	private long _companyId;
	private Date _modifiedDate;
	private long _anonymousUserId;
	private long _originalAnonymousUserId;
	private boolean _setOriginalAnonymousUserId;
	private long _ruleInstanceId;
	private long _originalRuleInstanceId;
	private boolean _setOriginalRuleInstanceId;
	private long _currentPlid;
	private boolean _finished;
	private long _columnBitmask;
	private UserJourney _escapedModel;
}