/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.content.targeting.rule.mail.keywords.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the KeywordMatch service. Represents a row in the &quot;CT_MK_KeywordMatch&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.content.targeting.rule.mail.keywords.model.impl.KeywordMatchModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.content.targeting.rule.mail.keywords.model.impl.KeywordMatchImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see KeywordMatch
 * @see com.liferay.content.targeting.rule.mail.keywords.model.impl.KeywordMatchImpl
 * @see com.liferay.content.targeting.rule.mail.keywords.model.impl.KeywordMatchModelImpl
 * @generated
 */
@ProviderType
public interface KeywordMatchModel extends BaseModel<KeywordMatch>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a keyword match model instance should use the {@link KeywordMatch} interface instead.
	 */

	/**
	 * Returns the primary key of this keyword match.
	 *
	 * @return the primary key of this keyword match
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this keyword match.
	 *
	 * @param primaryKey the primary key of this keyword match
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the keyword match ID of this keyword match.
	 *
	 * @return the keyword match ID of this keyword match
	 */
	public long getKeywordMatchId();

	/**
	 * Sets the keyword match ID of this keyword match.
	 *
	 * @param keywordMatchId the keyword match ID of this keyword match
	 */
	public void setKeywordMatchId(long keywordMatchId);

	/**
	 * Returns the company ID of this keyword match.
	 *
	 * @return the company ID of this keyword match
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this keyword match.
	 *
	 * @param companyId the company ID of this keyword match
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the modified date of this keyword match.
	 *
	 * @return the modified date of this keyword match
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this keyword match.
	 *
	 * @param modifiedDate the modified date of this keyword match
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the anonymous user ID of this keyword match.
	 *
	 * @return the anonymous user ID of this keyword match
	 */
	public long getAnonymousUserId();

	/**
	 * Sets the anonymous user ID of this keyword match.
	 *
	 * @param anonymousUserId the anonymous user ID of this keyword match
	 */
	public void setAnonymousUserId(long anonymousUserId);

	/**
	 * Returns the anonymous user uuid of this keyword match.
	 *
	 * @return the anonymous user uuid of this keyword match
	 */
	public String getAnonymousUserUuid();

	/**
	 * Sets the anonymous user uuid of this keyword match.
	 *
	 * @param anonymousUserUuid the anonymous user uuid of this keyword match
	 */
	public void setAnonymousUserUuid(String anonymousUserUuid);

	/**
	 * Returns the rule instance ID of this keyword match.
	 *
	 * @return the rule instance ID of this keyword match
	 */
	public long getRuleInstanceId();

	/**
	 * Sets the rule instance ID of this keyword match.
	 *
	 * @param ruleInstanceId the rule instance ID of this keyword match
	 */
	public void setRuleInstanceId(long ruleInstanceId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(KeywordMatch keywordMatch);

	@Override
	public int hashCode();

	@Override
	public CacheModel<KeywordMatch> toCacheModel();

	@Override
	public KeywordMatch toEscapedModel();

	@Override
	public KeywordMatch toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}